
[Debug]
	#
	# When loading files from datapacks, set this to true to log missing registry data for things like items.
	# Default: false
	log_missing_registry_data_for_datapacks = false

["Holiday Content"]
	#
	# Determines if Halloween cosmetic effects should happen.
	# Default: true
	allow_halloween_content = true
	#
	# Determines if Christmas cosmetic effects should happen.
	# Default: true
	allow_christmas_content = true

[Gatekeeper]
	#
	# The emerald cost for the Zeal Lighter sold by the Gatekeeper.
	# Default: 8
	zeal_lighter_cost = 8
	#
	# The percent chance of the Gatekeeper's house generating.
	# Default: 75
	#Range: 0 ~ 100
	gatekeeper_house_chance = 50

["Mod Compatibility"]
	#
	# A list of mods that are allowed to generate features in the Everbright and Everdawn.
	# This does not make them generate, it just allows them to pass the filter. 
	# Default: []
	# Example: ["minecraft", "farlanders", "botania"]
	allowed_mods_for_feature_gen = ["botania", "arsnoveau", "waystones", "alexsmobs"]
	#
	# A list of mobs that are allowed to spawn in the Everbright and Everdawn.
	# This does not make them spawn, it just allows them to pass the filter. 
	# Default: []
	# Example: ["minecraft:bee", "moolands:awful_cow", "alexs_mobs:grizzly_bear"]
	allowed_mobs_for_spawning = ["alexsmobs:seal", "alexsmobs:seagull", "alexsmobs:komodo_dragon", "alexsmobs:flutter", "alexsmobs:snow_leopard", "alexsmobs:crow", "alexsmobs:gorilla", "alexsmobs:tusklin", "alexsmobs:tasmanian_devil", "alexsmobs:rattlesnake", "alexsmobs:jerboa", "alexsmobs:alligator_snapping_turtle", "alexsmobs:platypus", "alexsmobs:terrapin", "alexsmobs:fly", "alexsmobs:shoebill", "alexsmobs:tarantula_hawk", "alexsmobs:warped_toad", "alexsmobs:gazelle", "alexsmobs:tiger", "alexsmobs:grizzlybear", "alexsmobs:moose", "alexsmobs:maned_wolf", "blueskies:elephant", "blueskies:froststalker", "alexsmobs:leafcutter_ant", "alexsmobs:raccoon", "alexsmobs:bald_eagle", "alexsmobs:lobster", "alexsmobs:orca", "alexsmobs:mantis_shrimp", "alexsmobs:giant_squid", "alexsmobs:cachalot_whale", "alexsmobs:mimic_octopus", "alexsmobs:comb_jelly", "alexsmobs:frilled_shark", "alexsmobs:hummingbird", "alexsmobs:crimson_mosquito", "alexsmobs:mungus", "alexsmobs:gelada_monkey"]

