#Range: 0 ~ 100
growingSpeed = 5
#Allowed Values: NO_DROP, INDEPENDENT, ONE_BY_ONE
fruitDropModeSingleplayer = "INDEPENDENT"
#Allowed Values: NO_DROP, INDEPENDENT, ONE_BY_ONE
fruitDropModeMultiplayer = "ONE_BY_ONE"
#Range: 2 ~ 10000
treesGenChunksInPlains = 400
#Range: 2 ~ 10000
treesGenChunksInForest = 150
#Range: 2 ~ 10000
treesGenChunksInJungle = 10
appleSaplingFromHeroOfTheVillage = true
villageAppleTreeWorldGen = true
fruitTreesWorldGen = true

[modules]
	cherry = true
	hybridization = true
	food = true

