
#Breeding Recipes Configuration
[breeding]

	[breeding.vanilla]
		axolotlSpawnEgg = "minecraft:axolotl_spawn_egg"
		beeSpawnEgg = "minecraft:bee_spawn_egg"
		catSpawnEgg = "minecraft:cat_spawn_egg"
		chickenSpawnEgg = "minecraft:chicken_spawn_egg"
		cowSpawnEgg = "minecraft:cow_spawn_egg"
		donkeySpawnEgg = "minecraft:donkey_spawn_egg"
		foxSpawnEgg = "minecraft:fox_spawn_egg"
		frogSpawnEgg = "minecraft:frog_spawn_egg"
		#Egg that frog lays after breeding
		frogeggResult = "minecraft:frogspawn"
		#Min amount of eggs that frog lays after breeding
		#Range: 1 ~ 64
		frogEggMinAmount = 1
		#Max amount of eggs that frog lays after breeding
		#Range: 1 ~ 64
		frogEggMaxAmount = 1
		goatSpawnEgg = "minecraft:goat_spawn_egg"
		hoglinSpawnEgg = "minecraft:hoglin_spawn_egg"
		horseSpawnEgg = "minecraft:horse_spawn_egg"
		llamaSpawnEgg = "minecraft:llama_spawn_egg"
		mooshroomSpawnEgg = "minecraft:mooshroom_spawn_egg"
		ocelotSpawnEgg = "minecraft:ocelot_spawn_egg"
		pandaSpawnEgg = "minecraft:panda_spawn_egg"
		pigSpawnEgg = "minecraft:pig_spawn_egg"
		rabbitSpawnEgg = "minecraft:rabbit_spawn_egg"
		sheepSpawnEgg = "minecraft:sheep_spawn_egg"
		striderSpawnEgg = "minecraft:strider_spawn_egg"
		trader_llamaSpawnEgg = "minecraft:trader_llama_spawn_egg"
		turtleSpawnEgg = "minecraft:turtle_spawn_egg"
		#Egg that turtle lays after breeding
		turtleeggResult = "minecraft:turtle_egg"
		#Min amount of eggs that turtle lays after breeding
		#Range: 1 ~ 64
		turtleEggMinAmount = 1
		#Max amount of eggs that turtle lays after breeding
		#Range: 1 ~ 64
		turtleEggMaxAmount = 4
		wolfSpawnEgg = "minecraft:wolf_spawn_egg"

		[breeding.vanilla.axolotl]
			#Ingredients required for axolotl breeding
			axolotlIngredients = "minecraft:tropical_fish_bucket"

		[breeding.vanilla.bee]
			#Ingredients required for bee breeding
			beeIngredients = "#minecraft:flowers"

		[breeding.vanilla.cat]
			#Ingredients required for cat breeding
			catIngredients = "minecraft:cod, minecraft:salmon"

		[breeding.vanilla.chicken]
			#Ingredients required for chicken breeding
			chickenIngredients = "minecraft:wheat_seeds, minecraft:pumpkin_seeds, minecraft:melon_seeds, minecraft:beetroot_seeds, minecraft:torchflower_seeds, minecraft:pitcher_pod"

		[breeding.vanilla.cow]
			#Ingredients required for cow breeding
			cowIngredients = "minecraft:wheat"

		[breeding.vanilla.donkey]
			#Ingredients required for donkey breeding
			donkeyIngredients = "minecraft:golden_apple, minecraft:enchanted_golden_apple, minecraft:golden_carrot"

		[breeding.vanilla.fox]
			#Ingredients required for fox breeding
			foxIngredients = "minecraft:sweet_berries, minecraft:glow_berries"

		[breeding.vanilla.frog]
			#Ingredients required for frog breeding
			frogIngredients = "minecraft:slime_ball"

		[breeding.vanilla.goat]
			#Ingredients required for goat breeding
			goatIngredients = "minecraft:wheat"

		[breeding.vanilla.hoglin]
			#Ingredients required for hoglin breeding
			hoglinIngredients = "minecraft:crimson_fungus"

		[breeding.vanilla.horse]
			#Ingredients required for horse breeding
			horseIngredients = "minecraft:golden_apple, minecraft:enchanted_golden_apple, minecraft:golden_carrot"

		[breeding.vanilla.llama]
			#Ingredients required for llama breeding
			llamaIngredients = "minecraft:hay_block"

		[breeding.vanilla.mooshroom]
			#Ingredients required for mooshroom breeding
			mooshroomIngredients = "minecraft:wheat"

		[breeding.vanilla.ocelot]
			#Ingredients required for ocelot breeding
			ocelotIngredients = "minecraft:cod, minecraft:salmon"

		[breeding.vanilla.panda]
			#Ingredients required for panda breeding
			pandaIngredients = "minecraft:bamboo"

		[breeding.vanilla.pig]
			#Ingredients required for pig breeding
			pigIngredients = "minecraft:carrot, minecraft:potato, minecraft:beetroot"

		[breeding.vanilla.rabbit]
			#Ingredients required for rabbit breeding
			rabbitIngredients = "minecraft:dandelion, minecraft:carrot, minecraft:golden_carrot"

		[breeding.vanilla.sheep]
			#Ingredients required for sheep breeding
			sheepIngredients = "minecraft:wheat"

		[breeding.vanilla.strider]
			#Ingredients required for strider breeding
			striderIngredients = "minecraft:warped_fungus"

		[breeding.vanilla.trader_llama]
			#Ingredients required for trader_llama breeding
			trader_llamaIngredients = "minecraft:hay_block"

		[breeding.vanilla.turtle]
			#Ingredients required for turtle breeding
			turtleIngredients = "minecraft:seagrass"

		[breeding.vanilla.wolf]
			#Ingredients required for wolf breeding
			wolfIngredients = "miskatonicmysteries:the_orb, farmersdelight:chicken_cuts, artifacts:eternal_steak, nethersdelight:hoglin_loin, twilightforest:hydra_chop, goodall:cooked_venison, bakery:strawberry_cake_slice, farmersdelight:bacon, rottencreatures:magma_rotten_flesh, ecologics:crab_meat, bakery:chocolate_tart_slice, betternether:stalagnate_bowl_wart, minecraft:cooked_chicken, twilightforest:cooked_meef, beachparty:cooked_mussel_meat, farmersdelight:cooked_mutton_chops, biomemakeover:cooked_toad, artifacts:everlasting_beef, beachparty:coconut_icecream, nethersdelight:strider_slice, farmersdelight:dog_food, beachparty:sweetberry_icecream, nethersdelight:hoglin_ear, beachparty:raw_pelican, naturalist:cooked_venison, naturalist:venison, beachparty:cooked_pelican, bakery:pudding_slice, candlelight:chicken_teriyaki, farmersdelight:cooked_bacon, bakery:sweetberry_cake_slice, minecraft:cooked_mutton, biomemakeover:raw_toad, minecraft:porkchop, minecraft:rotten_flesh, twilightforest:raw_meef, nethersdelight:ground_strider, farmersdelight:minced_beef, bakery:sweet_dough, minecraft:cooked_rabbit, nethersdelight:hoglin_sirloin, bakery:yeast, naturalist:lizard_tail, goodall:raw_venison, bakery:dough, minecraft:beef, candlelight:beef_tartare, minecraft:chicken, aylyth:wrongmeat, bewitchment:demon_heart, minecraft:cooked_beef, bakery:blank_cake, farmersdelight:cooked_chicken_cuts, naturalist:duck, miskatonicmysteries:cirrhosus_flesh, twilightforest:cooked_venison, naturalist:cooked_duck, aylyth:ympe_fruit, minecraft:rabbit, rottencreatures:frozen_rotten_flesh, bewitchment:grotesque_stew, farmersdelight:mutton_chops, minecraft:mutton, beachparty:chocolate_icecream, twilightforest:raw_venison, beachparty:raw_mussel_meat, minecraft:cooked_porkchop, bakery:chocolate_cake_slice, farmersdelight:beef_patty"

	[breeding.integration]

		[breeding.integration.lilwings]
			white_foxSpawnEgg = "lilwings:white_fox_egg"
			swamp_hopperSpawnEgg = "lilwings:swamp_hopper_egg"
			swallow_tailSpawnEgg = "lilwings:swallow_tail_egg"
			shroom_skipperSpawnEgg = "lilwings:shroom_skipper_egg"
			painted_pantherSpawnEgg = "lilwings:painted_panther_egg"
			ender_wingSpawnEgg = "lilwings:ender_wing_egg"
			crystal_puffSpawnEgg = "lilwings:crystal_puff_egg"
			cloudy_puffSpawnEgg = "lilwings:cloudy_puff_egg"
			butter_goldSpawnEgg = "lilwings:butter_gold_egg"
			aponiSpawnEgg = "lilwings:aponi_egg"
			red_appleflySpawnEgg = "lilwings:red_applefly_egg"
			graylingSpawnEgg = "lilwings:grayling_egg"

			[breeding.integration.lilwings.white_fox]
				#Ingredients required for white_fox breeding
				white_foxIngredients = "minecraft:lily_of_the_valley"

			[breeding.integration.lilwings.swamp_hopper]
				#Ingredients required for swamp_hopper breeding
				swamp_hopperIngredients = "minecraft:blue_orchid"

			[breeding.integration.lilwings.swallow_tail]
				#Ingredients required for swallow_tail breeding
				swallow_tailIngredients = "minecraft:wheat_seeds"

			[breeding.integration.lilwings.shroom_skipper]
				#Ingredients required for shroom_skipper breeding
				shroom_skipperIngredients = "minecraft:red_mushroom"

			[breeding.integration.lilwings.painted_panther]
				#Ingredients required for painted_panther breeding
				painted_pantherIngredients = "minecraft:cocoa_beans"

			[breeding.integration.lilwings.ender_wing]
				#Ingredients required for ender_wing breeding
				ender_wingIngredients = "minecraft:end_stone"

			[breeding.integration.lilwings.crystal_puff]
				#Ingredients required for crystal_puff breeding
				crystal_puffIngredients = "minecraft:allium"

			[breeding.integration.lilwings.cloudy_puff]
				#Ingredients required for cloudy_puff breeding
				cloudy_puffIngredients = "minecraft:azure_bluet"

			[breeding.integration.lilwings.butter_gold]
				#Ingredients required for butter_gold breeding
				butter_goldIngredients = "minecraft:dandelion"

			[breeding.integration.lilwings.aponi]
				#Ingredients required for aponi breeding
				aponiIngredients = "minecraft:brown_mushroom"

			[breeding.integration.lilwings.red_applefly]
				#Ingredients required for red_applefly breeding
				red_appleflyIngredients = "minecraft:apple"

			[breeding.integration.lilwings.grayling]
				#Ingredients required for grayling breeding
				graylingIngredients = "minecraft:moss_block"

		[breeding.integration.twilightforest]
			bighorn_sheepSpawnEgg = "twilightforest:bighorn_sheep_spawn_egg"
			boarSpawnEgg = "twilightforest:boar_spawn_egg"
			deerSpawnEgg = "twilightforest:deer_spawn_egg"
			dwarf_rabbitSpawnEgg = "twilightforest:dwarf_rabbit_spawn_egg"
			penguinSpawnEgg = "twilightforest:penguin_spawn_egg"

			[breeding.integration.twilightforest.bighorn_sheep]
				#Ingredients required for bighorn_sheep breeding
				bighorn_sheepIngredients = "minecraft:wheat"

			[breeding.integration.twilightforest.boar]
				#Ingredients required for boar breeding
				boarIngredients = "minecraft:beetroot, minecraft:carrot, minecraft:potato"

			[breeding.integration.twilightforest.deer]
				#Ingredients required for deer breeding
				deerIngredients = "minecraft:wheat"

			[breeding.integration.twilightforest.dwarf_rabbit]
				#Ingredients required for dwarf_rabbit breeding
				dwarf_rabbitIngredients = "minecraft:dandelion, minecraft:carrot, minecraft:golden_carrot"

			[breeding.integration.twilightforest.penguin]
				#Ingredients required for penguin breeding
				penguinIngredients = "minecraft:cod"

		[breeding.integration.ecologics]
			camelSpawnEgg = "ecologics:camel_spawn_egg"
			penguinSpawnEgg = "ecologics:penguin_spawn_egg"
			squirrelSpawnEgg = "ecologics:squirrel_spawn_egg"

			[breeding.integration.ecologics.camel]
				#Ingredients required for camel breeding
				camelIngredients = "ecologics:prickly_pear"

			[breeding.integration.ecologics.penguin]
				#Ingredients required for penguin breeding
				penguinIngredients = "minecraft:cod, minecraft:salmon"

			[breeding.integration.ecologics.squirrel]
				#Ingredients required for squirrel breeding
				squirrelIngredients = "minecraft:honeycomb"

		[breeding.integration.naturalist]
			alligatorSpawnEgg = "naturalist:alligator_spawn_egg"
			bearSpawnEgg = "naturalist:bear_spawn_egg"
			boarSpawnEgg = "naturalist:boar_spawn_egg"
			butterflySpawnEgg = "naturalist:butterfly_spawn_egg"
			deerSpawnEgg = "naturalist:deer_spawn_egg"
			duckSpawnEgg = "naturalist:duck_spawn_egg"
			giraffeSpawnEgg = "naturalist:giraffe_spawn_egg"
			tortoiseSpawnEgg = "naturalist:tortoise_spawn_egg"

			[breeding.integration.naturalist.alligator]
				#Ingredients required for alligator breeding
				alligatorIngredients = "#naturalist:alligator_food_items"
				#Egg that alligator lays after breeding
				alligatoreggResult = "naturalist:alligator_egg"
				#Min amount of eggs that alligator lays after breeding
				#Range: 1 ~ 64
				alligatorEggMinAmount = 1
				#Max amount of eggs that alligator lays after breeding
				#Range: 1 ~ 64
				alligatorEggMaxAmount = 4

			[breeding.integration.naturalist.bear]
				#Ingredients required for bear breeding
				bearIngredients = "#naturalist:bear_tempt_items"

			[breeding.integration.naturalist.boar]
				#Ingredients required for boar breeding
				boarIngredients = "#naturalist:boar_food_items"

			[breeding.integration.naturalist.butterfly]
				#Ingredients required for butterfly breeding
				butterflyIngredients = "#minecraft:flowers"

			[breeding.integration.naturalist.deer]
				#Ingredients required for deer breeding
				deerIngredients = "minecraft:apple"

			[breeding.integration.naturalist.duck]
				#Ingredients required for duck breeding
				duckIngredients = "#naturalist:duck_food_items"

			[breeding.integration.naturalist.giraffe]
				#Ingredients required for giraffe breeding
				giraffeIngredients = "minecraft:hay_block"

			[breeding.integration.naturalist.tortoise]
				#Ingredients required for tortoise breeding
				tortoiseIngredients = "#naturalist:tortoise_tempt_items"
				#Egg that tortoise lays after breeding
				tortoiseeggResult = "naturalist:tortoise_egg"
				#Min amount of eggs that tortoise lays after breeding
				#Range: 1 ~ 64
				tortoiseEggMinAmount = 1
				#Max amount of eggs that tortoise lays after breeding
				#Range: 1 ~ 64
				tortoiseEggMaxAmount = 4

